export const HOME_GET_ALL_SERIE_BEGIN = 'HOME_GET_ALL_SERIE_BEGIN';
export const HOME_GET_ALL_SERIE_SUCCESS = 'HOME_GET_ALL_SERIE_SUCCESS';
export const HOME_GET_ALL_SERIE_FAILURE = 'HOME_GET_ALL_SERIE_FAILURE';
export const HOME_GET_ALL_SERIE_DISMISS_ERROR = 'HOME_GET_ALL_SERIE_DISMISS_ERROR';
